In [4]:
import pandas as pd
import pickle
import torch

In [7]:
product_data = pd.read_csv('dataset/product_data_preprocessed.csv')
product_data.head()

,cod_modelo_color,des_filename,des_agrup_color_eng_BLUE,des_agrup_color_eng_BROWN,des_agrup_color_eng_GREEN,des_agrup_color_eng_GREY,des_agrup_color_eng_ORANGE,des_agrup_color_eng_PINK,des_agrup_color_eng_PURPLE,des_agrup_color_eng_RED,...,des_product_type_Tie,des_product_type_Top,des_product_type_Totes bag,des_product_type_Trainers,des_product_type_Trenchcoat,des_product_type_Trousers,des_product_type_Turban,des_product_type_Umbrella,des_product_type_Vest,des_product_type_Wallet
0,41085800-02,2019_41085800_02.jpg,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,53000586-TO,2019_53000586_TO.jpg,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,53030601-81,2019_53030601_81.jpg,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,53050730-15,2019_53050730_15.jpg,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,53070773-70,2019_53070773_70.jpg,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
with open('dataset/compatibilities.pickle', 'rb') as f:
    compatibilities = pickle.load(f)

labels = pd.DataFrame.from_dict(compatibilities.items())
labels.columns = ['cod_modelo_color', 'community_id']
labels = labels.merge(product_data, on='cod_modelo_color')

labels.head()

,cod_modelo_color,community_id,des_filename,des_agrup_color_eng_BLUE,des_agrup_color_eng_BROWN,des_agrup_color_eng_GREEN,des_agrup_color_eng_GREY,des_agrup_color_eng_ORANGE,des_agrup_color_eng_PINK,des_agrup_color_eng_PURPLE,...,des_product_type_Tie,des_product_type_Top,des_product_type_Totes bag,des_product_type_Trainers,des_product_type_Trenchcoat,des_product_type_Trousers,des_product_type_Turban,des_product_type_Umbrella,des_product_type_Vest,des_product_type_Wallet
0,53070992-01,0,2019_53070992_01.jpg,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,51070902-02,0,2019_51070902_02.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,53010605-09,0,2019_53010605_09.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,53000578-01,0,2019_53000578_01.jpg,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,53020724-14,0,2019_53020724_14.jpg,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [15]:
X = labels.drop(['community_id', 'cod_modelo_color'], axis=1)
y = labels['community_id']

(8741, 112)

In [ ]:
with open('dataset/image_features.pickle', 'rb') as f:
    image_features = pickle.load(f)
    
X = X.merge(image_features, on = 'des_filename').drop(['des_filename'], axis=1)

In [ ]:
X.to_csv('X.csv', index=False)
y.to_csv('y.csv', index=False)

In [19]:
x  = pd.read_csv('dataset/product_data.csv')
x

,cod_modelo_color,cod_color_code,des_color_specification_esp,des_agrup_color_eng,des_sex,des_age,des_line,des_fabric,des_product_category,des_product_aggregated_family,des_product_family,des_product_type,des_filename
0,41085800-02,02,OFFWHITE,WHITE,Female,Adult,SHE,P-PLANA,Bottoms,Trousers & leggings,Trousers,Trousers,datathon/images/2019_41085800_02.jpg
1,53000586-TO,TO,TEJANO OSCURO,BLUE,Female,Adult,SHE,J-JEANS,Bottoms,Jeans,Jeans,Jeans,datathon/images/2019_53000586_TO.jpg
2,53030601-81,81,ROSA PASTEL,PINK,Female,Adult,SHE,P-PLANA,"Dresses, jumpsuits and Complete set",Dresses and jumpsuits,Dresses,Dress,datathon/images/2019_53030601_81.jpg
3,53050730-15,15,MOSTAZA,YELLOW,Female,Adult,SHE,P-PLANA,"Dresses, jumpsuits and Complete set",Dresses and jumpsuits,Dresses,Dress,datathon/images/2019_53050730_15.jpg
4,53070773-70,70,ROJO,RED,Female,Adult,SHE,P-PLANA,Tops,Shirts,Shirt,Shirt,datathon/images/2019_53070773_70.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9217,57066027-99,99,NEGRO,GREY,Female,Adult,SHE,P-PLANA,"Dresses, jumpsuits and Complete set",Dresses and jumpsuits,Dresses,Dress,datathon/images/2023_57066027_99.jpg
9218,57076028-92,92,GRIS,GREY,Female,Adult,SHE,P-PLANA,Bottoms,Skirts and shorts,Shorts,Shorts,datathon/images/2023_57076028_92.jpg
9219,57068275-05,05,CRUDO,WHITE,Female,Adult,SHE,C-COMPLEMENTOS,"Accesories, Swim and Intimate",Swim and intimate,Intimate,Socks,datathon/images/2023_57068275_05.jpg
9220,57067125-78,78,BURDEOS,RED,Female,Adult,SHE,K-CIRCULAR,"Dresses, jumpsuits and Complete set",Dresses and jumpsuits,Dresses,Dress,datathon/images/2023_57067125_78.jpg
9221,57039120-PL,PL,PLATA,GREY,Female,Adult,SHE,T-TRICOT,Tops,Tops,Tops,Top,datathon/images/2023_57039120_PL.jpg